ci: overhaul
Change-Id: I00abc72f90860a61f740e298736722c66211fb74
Signed-off-by: gyabii <gyabii@proton.me>

diff --git a/.github/workflows/build-plain.yml b/.github/workflows/build-plain.yml
--- a/.github/workflows/build-plain.yml
+++ b/.github/workflows/build-plain.yml
@@ -5,6 +5,8 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    permissions:
+       contents: write
     steps:
       - name: Checkout the repository
         uses: actions/checkout@v6
@@ -13,7 +15,7 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y --no-install-recommends \
-            bc bison build-essential curl flex \
+            bc bison build-essential curl flex gh \
             g++-multilib gcc-multilib git gnupg \
             lib32readline-dev lib32z1-dev \
             libelf-dev liblz4-tool libssl-dev \
@@ -40,25 +42,47 @@ jobs:
           git config --global user.name "gyabii"
           chmod +x scripts/build.sh
           ./scripts/build.sh 2>&1 | tee "$GITHUB_WORKSPACE/build.log"
+          if [ ! -f "out/arch/arm64/boot/Image.gz" ]; then
+            echo "ERROR: Kernel compilation failed! out/arch/arm64/boot/Image.gz not found."
+            exit 1
+          fi
 
       - name: Package image with AnyKernel3
         id: package
         run: |
-          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
+          BUILD_DATE="$(date)"
+          TIMESTAMP="$(date +%d%m%y-%H%M%S)"
           set -euxo pipefail
           unzip "anykernel.zip" -d anykernel/
           cp out/arch/arm64/boot/Image.gz anykernel/
-          # Build final name
+          touch -a -m -t 200901010000.00 "anykernel/Image.gz"
           ZIP_NAME="common-5.15.${KERNEL_VERSION}-gyabii_plain-$(date +%d%m%y-%H%M%S)"
           cd anykernel
           zip -r0 ../"${ZIP_NAME}".zip ./*
-          echo "zip_path=$GITHUB_WORKSPACE/${ZIP_NAME}.zip" >> "$GITHUB_OUTPUT"
-          echo "zip_name=${ZIP_NAME}" >> "$GITHUB_OUTPUT"
           cd ..
+          HASH=$(sha256sum "${ZIP_NAME}.zip" | awk '{print $1}')
+          cat >> "release_notes.md" << EOF
+          Common ReSukiSU 5.15.${KERNEL_VERSION} kernel
+          Built at: ${BUILD_DATE}
+          
+          sha256:
+          \`\`\`
+          ${HASH}
+          \`\`\`
+          EOF
+          echo "zip_full_path=$GITHUB_WORKSPACE/${ZIP_NAME}.zip" >> "$GITHUB_OUTPUT"
+          echo "zip_name=${ZIP_NAME}.zip" >> "$GITHUB_OUTPUT"
+          echo "tag_name=common-plain-5.15.${KERNEL_VERSION}-${TIMESTAMP}" >> "$GITHUB_OUTPUT"
 
       - name: Upload the flashable kernel
         uses: actions/upload-artifact@v7
         with:
-          name: ${{steps.package.outputs.zip_name}}
+          name: ${{ steps.package.outputs.zip_name }}
           path: anykernel/
-          
+
+      - name: Publish to GitHub Release
+        uses: softprops/action-gh-release@v3
+        with:
+          tag_name: ${{ steps.package.outputs.tag_name }}
+          files: ${{ steps.package.outputs.zip_full_path }}
+          body_path: release_notes.md
